export const ACTIONS = Object.freeze({
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  LIST: 'list',
});

export const RESOURCES = Object.freeze({
  USERS: 'users',
  ROLES: 'roles',
  PERMISSIONS: 'permissions',
  AUTH: 'auth',
  AUDIT: 'audit',
});

export function perm(resource, action) {
  return `${resource}:${action}`;
}

export const CORE_PERMS = Object.freeze({
  USERS_CREATE: perm(RESOURCES.USERS, ACTIONS.CREATE),
  USERS_READ: perm(RESOURCES.USERS, ACTIONS.READ),
  USERS_UPDATE: perm(RESOURCES.USERS, ACTIONS.UPDATE),
  USERS_DELETE: perm(RESOURCES.USERS, ACTIONS.DELETE),
  USERS_LIST: perm(RESOURCES.USERS, ACTIONS.LIST),

  ROLES_CREATE: perm(RESOURCES.ROLES, ACTIONS.CREATE),
  ROLES_READ: perm(RESOURCES.ROLES, ACTIONS.READ),
  ROLES_UPDATE: perm(RESOURCES.ROLES, ACTIONS.UPDATE),
  ROLES_DELETE: perm(RESOURCES.ROLES, ACTIONS.DELETE),
  ROLES_LIST: perm(RESOURCES.ROLES, ACTIONS.LIST),

  PERMISSIONS_CREATE: perm(RESOURCES.PERMISSIONS, ACTIONS.CREATE),
  PERMISSIONS_READ: perm(RESOURCES.PERMISSIONS, ACTIONS.READ),
  PERMISSIONS_UPDATE: perm(RESOURCES.PERMISSIONS, ACTIONS.UPDATE),
  PERMISSIONS_DELETE: perm(RESOURCES.PERMISSIONS, ACTIONS.DELETE),
  PERMISSIONS_LIST: perm(RESOURCES.PERMISSIONS, ACTIONS.LIST),

  AUDIT_LIST: perm(RESOURCES.AUDIT, ACTIONS.LIST),
  AUDIT_READ: perm(RESOURCES.AUDIT, ACTIONS.READ),
});
